version: 0.2

phases:
    install:
        commands:
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
            - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - echo $AWS_DEFAULT_REGION
            - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
            - REPOSITORY_URI=809038661221.dkr.ecr.ap-east-1.amazonaws.com/sfx-ecr-repo
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - echo $COMMIT_HASH
            - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
            - echo Build started on `date`
            - go env
            - cd projects/sfx-server
            - make
            - echo Building the Docker image...
            - echo $REPOSITORY_URI
            - echo $IMAGE_TAG
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - docker images
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
            - printf '[{"name":"sfx-fargate-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
            - ls -a
            - cat imageDetail.json
            - cat imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json
        - imageDetail.json