version: 0.2

phases:
    pre_build:
        commands:
            - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - echo $COMMIT_HASH
    build:
        commands:
            - echo Build started on `date`
            - make
artifacts:
    files:
        - dist