version: 0.2

phases:
    build:
        commands:
            - echo Build started on `date`
            - chmod +x build.sh
            - ./build.sh
            
artifacts:
    files:
        - dist/**/*
        - codebuild/**/*