version: 0.2

phases:
    build:
        commands:
            - echo Build started on `date`
            - echo Asia/Shanghai > /etc/timezone
            - apt-get update
            - apt-get install -y tzdata
            - apt-get install -y gnupg2
            - apt-get install -y ca-certificates
            - apt-get install -y build-essential
            - apt-get install -y golang-go
            - go version
            - make
            
artifacts:
    files:
        - dist/**/*
        - codebuild/**/*