#include <iostream>
#include "stdio.h"
#include "libsome_api.h"

int main(int argc, char** argv) {
  libsome_ExportedSymbols* lib = libsome_symbols();

  const char* str = "{\n"
                    "                \"ops\": [\n"
                    "                    {\n"
                    "                        \"insert\": \"随机文本\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"啊哈哈又\\n一段文本\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"标题一\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"header\": 1\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"丰富的发是\\n的\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"link\": \"https://www.jetbrains.com/idea/\"\n"
                    "                        },\n"
                    "                        \"insert\": \"IntelliJ IDEA\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"编辑\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"italic\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"斜体\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"italic\": true,\n"
                    "                            \"bold\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"加粗\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"font\": \"serif\"\n"
                    "                        },\n"
                    "                        \"insert\": \"更换字体\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"strike\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"删除线\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"underline\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"下划线\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"color\": \"#e60000\"\n"
                    "                        },\n"
                    "                        \"insert\": \"颜色字体\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"color\": \"#ffffff\",\n"
                    "                            \"background\": \"#66b966\"\n"
                    "                        },\n"
                    "                        \"insert\": \"背景色\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n居中对齐\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"align\": \"center\"\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"居右对齐\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"align\": \"right\"\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n引用块\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"blockquote\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"代码块\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"code-block\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"wu\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"code-block\": true\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"wu\\n无序列表\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"list\": \"bullet\"\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"无序列表2\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"attributes\": {\n"
                    "                            \"list\": \"bullet\"\n"
                    "                        },\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    },\n"
                    "                    {\n"
                    "                        \"insert\": \"\\n\"\n"
                    "                    }\n"
                    "                ]\n"
                    "            }";
  auto deltaSerializer = lib -> kotlin.root.parchment.DeltaSerializer.DeltaSerializer();
  libsome_kref_parchment_Node node = lib -> kotlin.root.parchment
      .DeltaSerializer.parseToNode(deltaSerializer, str);
  auto newInstance = lib -> kotlin.root.parchment.NodeSerializer.NodeSerializer();
  const char* response = lib -> kotlin.root.parchment.NodeSerializer.
      encodeToJsonString(newInstance, node);
  printf("%s\n", response);
  lib->DisposeString(response);
  return 0;
}