package utils

object StringUtils {
    private val htmlEncodeChars = HashMap<Char, String>()

    fun encodeHtml(source: String?): String? {
        return encode(source, htmlEncodeChars)
    }

    private fun encode(source: String?, encodingTable: HashMap<Char, String>?): String? {
        if (null == source) {
            return null
        }
        if (null == encodingTable) {
            return source
        }
        var encoded_string: StringBuilder? = null
        val string_to_encode_array = source.toCharArray()
        var last_match = -1
        var difference: Int
        for (i in string_to_encode_array.indices) {
            val char_to_encode = string_to_encode_array[i]
            if (encodingTable.containsKey(char_to_encode)) {
                if (null == encoded_string) {
                    encoded_string = StringBuilder(source.length)
                }
                difference = i - (last_match + 1)
                if (difference > 0) {
                    encoded_string.append(string_to_encode_array, last_match + 1, difference)
                }
                encoded_string.append(encodingTable[char_to_encode])
                last_match = i
            }
        }
        return if (null == encoded_string) {
            source
        } else {
            difference = string_to_encode_array.size - (last_match + 1)
            if (difference > 0) {
                encoded_string.append(string_to_encode_array, last_match + 1, difference)
            }
            encoded_string.toString()
        }
    }

    init {

        // Special characters for HTML
        htmlEncodeChars['\u0026'] = "&amp;"
        htmlEncodeChars['\u003C'] = "&lt;"
        htmlEncodeChars['\u003E'] = "&gt;"
        htmlEncodeChars['\u0022'] = "&quot;"
        htmlEncodeChars['\u0152'] = "&OElig;"
        htmlEncodeChars['\u0153'] = "&oelig;"
        htmlEncodeChars['\u0160'] = "&Scaron;"
        htmlEncodeChars['\u0161'] = "&scaron;"
        htmlEncodeChars['\u0178'] = "&Yuml;"
        htmlEncodeChars['\u02C6'] = "&circ;"
        htmlEncodeChars['\u02DC'] = "&tilde;"
        htmlEncodeChars['\u2002'] = "&ensp;"
        htmlEncodeChars['\u2003'] = "&emsp;"
        htmlEncodeChars['\u2009'] = "&thinsp;"
        htmlEncodeChars['\u200C'] = "&zwnj;"
        htmlEncodeChars['\u200D'] = "&zwj;"
        htmlEncodeChars['\u200E'] = "&lrm;"
        htmlEncodeChars['\u200F'] = "&rlm;"
        htmlEncodeChars['\u2013'] = "&ndash;"
        htmlEncodeChars['\u2014'] = "&mdash;"
        htmlEncodeChars['\u2018'] = "&lsquo;"
        htmlEncodeChars['\u2019'] = "&rsquo;"
        htmlEncodeChars['\u201A'] = "&sbquo;"
        htmlEncodeChars['\u201C'] = "&ldquo;"
        htmlEncodeChars['\u201D'] = "&rdquo;"
        htmlEncodeChars['\u201E'] = "&bdquo;"
        htmlEncodeChars['\u2020'] = "&dagger;"
        htmlEncodeChars['\u2021'] = "&Dagger;"
        htmlEncodeChars['\u2030'] = "&permil;"
        htmlEncodeChars['\u2039'] = "&lsaquo;"
        htmlEncodeChars['\u203A'] = "&rsaquo;"
        htmlEncodeChars['\u20AC'] = "&euro;"

        // Character entity references for ISO 8859-1 characters
        htmlEncodeChars['\u00A0'] = "&nbsp;"
        htmlEncodeChars['\u00A1'] = "&iexcl;"
        htmlEncodeChars['\u00A2'] = "&cent;"
        htmlEncodeChars['\u00A3'] = "&pound;"
        htmlEncodeChars['\u00A4'] = "&curren;"
        htmlEncodeChars['\u00A5'] = "&yen;"
        htmlEncodeChars['\u00A6'] = "&brvbar;"
        htmlEncodeChars['\u00A7'] = "&sect;"
        htmlEncodeChars['\u00A8'] = "&uml;"
        htmlEncodeChars['\u00A9'] = "&copy;"
        htmlEncodeChars['\u00AA'] = "&ordf;"
        htmlEncodeChars['\u00AB'] = "&laquo;"
        htmlEncodeChars['\u00AC'] = "&not;"
        htmlEncodeChars['\u00AD'] = "&shy;"
        htmlEncodeChars['\u00AE'] = "&reg;"
        htmlEncodeChars['\u00AF'] = "&macr;"
        htmlEncodeChars['\u00B0'] = "&deg;"
        htmlEncodeChars['\u00B1'] = "&plusmn;"
        htmlEncodeChars['\u00B2'] = "&sup2;"
        htmlEncodeChars['\u00B3'] = "&sup3;"
        htmlEncodeChars['\u00B4'] = "&acute;"
        htmlEncodeChars['\u00B5'] = "&micro;"
        htmlEncodeChars['\u00B6'] = "&para;"
        htmlEncodeChars['\u00B7'] = "&middot;"
        htmlEncodeChars['\u00B8'] = "&cedil;"
        htmlEncodeChars['\u00B9'] = "&sup1;"
        htmlEncodeChars['\u00BA'] = "&ordm;"
        htmlEncodeChars['\u00BB'] = "&raquo;"
        htmlEncodeChars['\u00BC'] = "&frac14;"
        htmlEncodeChars['\u00BD'] = "&frac12;"
        htmlEncodeChars['\u00BE'] = "&frac34;"
        htmlEncodeChars['\u00BF'] = "&iquest;"
        htmlEncodeChars['\u00C0'] = "&Agrave;"
        htmlEncodeChars['\u00C1'] = "&Aacute;"
        htmlEncodeChars['\u00C2'] = "&Acirc;"
        htmlEncodeChars['\u00C3'] = "&Atilde;"
        htmlEncodeChars['\u00C4'] = "&Auml;"
        htmlEncodeChars['\u00C5'] = "&Aring;"
        htmlEncodeChars['\u00C6'] = "&AElig;"
        htmlEncodeChars['\u00C7'] = "&Ccedil;"
        htmlEncodeChars['\u00C8'] = "&Egrave;"
        htmlEncodeChars['\u00C9'] = "&Eacute;"
        htmlEncodeChars['\u00CA'] = "&Ecirc;"
        htmlEncodeChars['\u00CB'] = "&Euml;"
        htmlEncodeChars['\u00CC'] = "&Igrave;"
        htmlEncodeChars['\u00CD'] = "&Iacute;"
        htmlEncodeChars['\u00CE'] = "&Icirc;"
        htmlEncodeChars['\u00CF'] = "&Iuml;"
        htmlEncodeChars['\u00D0'] = "&ETH;"
        htmlEncodeChars['\u00D1'] = "&Ntilde;"
        htmlEncodeChars['\u00D2'] = "&Ograve;"
        htmlEncodeChars['\u00D3'] = "&Oacute;"
        htmlEncodeChars['\u00D4'] = "&Ocirc;"
        htmlEncodeChars['\u00D5'] = "&Otilde;"
        htmlEncodeChars['\u00D6'] = "&Ouml;"
        htmlEncodeChars['\u00D7'] = "&times;"
        htmlEncodeChars['\u00D8'] = "&Oslash;"
        htmlEncodeChars['\u00D9'] = "&Ugrave;"
        htmlEncodeChars['\u00DA'] = "&Uacute;"
        htmlEncodeChars['\u00DB'] = "&Ucirc;"
        htmlEncodeChars['\u00DC'] = "&Uuml;"
        htmlEncodeChars['\u00DD'] = "&Yacute;"
        htmlEncodeChars['\u00DE'] = "&THORN;"
        htmlEncodeChars['\u00DF'] = "&szlig;"
        htmlEncodeChars['\u00E0'] = "&agrave;"
        htmlEncodeChars['\u00E1'] = "&aacute;"
        htmlEncodeChars['\u00E2'] = "&acirc;"
        htmlEncodeChars['\u00E3'] = "&atilde;"
        htmlEncodeChars['\u00E4'] = "&auml;"
        htmlEncodeChars['\u00E5'] = "&aring;"
        htmlEncodeChars['\u00E6'] = "&aelig;"
        htmlEncodeChars['\u00E7'] = "&ccedil;"
        htmlEncodeChars['\u00E8'] = "&egrave;"
        htmlEncodeChars['\u00E9'] = "&eacute;"
        htmlEncodeChars['\u00EA'] = "&ecirc;"
        htmlEncodeChars['\u00EB'] = "&euml;"
        htmlEncodeChars['\u00EC'] = "&igrave;"
        htmlEncodeChars['\u00ED'] = "&iacute;"
        htmlEncodeChars['\u00EE'] = "&icirc;"
        htmlEncodeChars['\u00EF'] = "&iuml;"
        htmlEncodeChars['\u00F0'] = "&eth;"
        htmlEncodeChars['\u00F1'] = "&ntilde;"
        htmlEncodeChars['\u00F2'] = "&ograve;"
        htmlEncodeChars['\u00F3'] = "&oacute;"
        htmlEncodeChars['\u00F4'] = "&ocirc;"
        htmlEncodeChars['\u00F5'] = "&otilde;"
        htmlEncodeChars['\u00F6'] = "&ouml;"
        htmlEncodeChars['\u00F7'] = "&divide;"
        htmlEncodeChars['\u00F8'] = "&oslash;"
        htmlEncodeChars['\u00F9'] = "&ugrave;"
        htmlEncodeChars['\u00FA'] = "&uacute;"
        htmlEncodeChars['\u00FB'] = "&ucirc;"
        htmlEncodeChars['\u00FC'] = "&uuml;"
        htmlEncodeChars['\u00FD'] = "&yacute;"
        htmlEncodeChars['\u00FE'] = "&thorn;"
        htmlEncodeChars['\u00FF'] = "&yuml;"

        // Mathematical, Greek and Symbolic characters for HTML
        htmlEncodeChars['\u0192'] = "&fnof;"
        htmlEncodeChars['\u0391'] = "&Alpha;"
        htmlEncodeChars['\u0392'] = "&Beta;"
        htmlEncodeChars['\u0393'] = "&Gamma;"
        htmlEncodeChars['\u0394'] = "&Delta;"
        htmlEncodeChars['\u0395'] = "&Epsilon;"
        htmlEncodeChars['\u0396'] = "&Zeta;"
        htmlEncodeChars['\u0397'] = "&Eta;"
        htmlEncodeChars['\u0398'] = "&Theta;"
        htmlEncodeChars['\u0399'] = "&Iota;"
        htmlEncodeChars['\u039A'] = "&Kappa;"
        htmlEncodeChars['\u039B'] = "&Lambda;"
        htmlEncodeChars['\u039C'] = "&Mu;"
        htmlEncodeChars['\u039D'] = "&Nu;"
        htmlEncodeChars['\u039E'] = "&Xi;"
        htmlEncodeChars['\u039F'] = "&Omicron;"
        htmlEncodeChars['\u03A0'] = "&Pi;"
        htmlEncodeChars['\u03A1'] = "&Rho;"
        htmlEncodeChars['\u03A3'] = "&Sigma;"
        htmlEncodeChars['\u03A4'] = "&Tau;"
        htmlEncodeChars['\u03A5'] = "&Upsilon;"
        htmlEncodeChars['\u03A6'] = "&Phi;"
        htmlEncodeChars['\u03A7'] = "&Chi;"
        htmlEncodeChars['\u03A8'] = "&Psi;"
        htmlEncodeChars['\u03A9'] = "&Omega;"
        htmlEncodeChars['\u03B1'] = "&alpha;"
        htmlEncodeChars['\u03B2'] = "&beta;"
        htmlEncodeChars['\u03B3'] = "&gamma;"
        htmlEncodeChars['\u03B4'] = "&delta;"
        htmlEncodeChars['\u03B5'] = "&epsilon;"
        htmlEncodeChars['\u03B6'] = "&zeta;"
        htmlEncodeChars['\u03B7'] = "&eta;"
        htmlEncodeChars['\u03B8'] = "&theta;"
        htmlEncodeChars['\u03B9'] = "&iota;"
        htmlEncodeChars['\u03BA'] = "&kappa;"
        htmlEncodeChars['\u03BB'] = "&lambda;"
        htmlEncodeChars['\u03BC'] = "&mu;"
        htmlEncodeChars['\u03BD'] = "&nu;"
        htmlEncodeChars['\u03BE'] = "&xi;"
        htmlEncodeChars['\u03BF'] = "&omicron;"
        htmlEncodeChars['\u03C0'] = "&pi;"
        htmlEncodeChars['\u03C1'] = "&rho;"
        htmlEncodeChars['\u03C2'] = "&sigmaf;"
        htmlEncodeChars['\u03C3'] = "&sigma;"
        htmlEncodeChars['\u03C4'] = "&tau;"
        htmlEncodeChars['\u03C5'] = "&upsilon;"
        htmlEncodeChars['\u03C6'] = "&phi;"
        htmlEncodeChars['\u03C7'] = "&chi;"
        htmlEncodeChars['\u03C8'] = "&psi;"
        htmlEncodeChars['\u03C9'] = "&omega;"
        htmlEncodeChars['\u03D1'] = "&thetasym;"
        htmlEncodeChars['\u03D2'] = "&upsih;"
        htmlEncodeChars['\u03D6'] = "&piv;"
        htmlEncodeChars['\u2022'] = "&bull;"
        htmlEncodeChars['\u2026'] = "&hellip;"
        htmlEncodeChars['\u2032'] = "&prime;"
        htmlEncodeChars['\u2033'] = "&Prime;"
        htmlEncodeChars['\u203E'] = "&oline;"
        htmlEncodeChars['\u2044'] = "&frasl;"
        htmlEncodeChars['\u2118'] = "&weierp;"
        htmlEncodeChars['\u2111'] = "&image;"
        htmlEncodeChars['\u211C'] = "&real;"
        htmlEncodeChars['\u2122'] = "&trade;"
        htmlEncodeChars['\u2135'] = "&alefsym;"
        htmlEncodeChars['\u2190'] = "&larr;"
        htmlEncodeChars['\u2191'] = "&uarr;"
        htmlEncodeChars['\u2192'] = "&rarr;"
        htmlEncodeChars['\u2193'] = "&darr;"
        htmlEncodeChars['\u2194'] = "&harr;"
        htmlEncodeChars['\u21B5'] = "&crarr;"
        htmlEncodeChars['\u21D0'] = "&lArr;"
        htmlEncodeChars['\u21D1'] = "&uArr;"
        htmlEncodeChars['\u21D2'] = "&rArr;"
        htmlEncodeChars['\u21D3'] = "&dArr;"
        htmlEncodeChars['\u21D4'] = "&hArr;"
        htmlEncodeChars['\u2200'] = "&forall;"
        htmlEncodeChars['\u2202'] = "&part;"
        htmlEncodeChars['\u2203'] = "&exist;"
        htmlEncodeChars['\u2205'] = "&empty;"
        htmlEncodeChars['\u2207'] = "&nabla;"
        htmlEncodeChars['\u2208'] = "&isin;"
        htmlEncodeChars['\u2209'] = "&notin;"
        htmlEncodeChars['\u220B'] = "&ni;"
        htmlEncodeChars['\u220F'] = "&prod;"
        htmlEncodeChars['\u2211'] = "&sum;"
        htmlEncodeChars['\u2212'] = "&minus;"
        htmlEncodeChars['\u2217'] = "&lowast;"
        htmlEncodeChars['\u221A'] = "&radic;"
        htmlEncodeChars['\u221D'] = "&prop;"
        htmlEncodeChars['\u221E'] = "&infin;"
        htmlEncodeChars['\u2220'] = "&ang;"
        htmlEncodeChars['\u2227'] = "&and;"
        htmlEncodeChars['\u2228'] = "&or;"
        htmlEncodeChars['\u2229'] = "&cap;"
        htmlEncodeChars['\u222A'] = "&cup;"
        htmlEncodeChars['\u222B'] = "&int;"
        htmlEncodeChars['\u2234'] = "&there4;"
        htmlEncodeChars['\u223C'] = "&sim;"
        htmlEncodeChars['\u2245'] = "&cong;"
        htmlEncodeChars['\u2248'] = "&asymp;"
        htmlEncodeChars['\u2260'] = "&ne;"
        htmlEncodeChars['\u2261'] = "&equiv;"
        htmlEncodeChars['\u2264'] = "&le;"
        htmlEncodeChars['\u2265'] = "&ge;"
        htmlEncodeChars['\u2282'] = "&sub;"
        htmlEncodeChars['\u2283'] = "&sup;"
        htmlEncodeChars['\u2284'] = "&nsub;"
        htmlEncodeChars['\u2286'] = "&sube;"
        htmlEncodeChars['\u2287'] = "&supe;"
        htmlEncodeChars['\u2295'] = "&oplus;"
        htmlEncodeChars['\u2297'] = "&otimes;"
        htmlEncodeChars['\u22A5'] = "&perp;"
        htmlEncodeChars['\u22C5'] = "&sdot;"
        htmlEncodeChars['\u2308'] = "&lceil;"
        htmlEncodeChars['\u2309'] = "&rceil;"
        htmlEncodeChars['\u230A'] = "&lfloor;"
        htmlEncodeChars['\u230B'] = "&rfloor;"
        htmlEncodeChars['\u2329'] = "&lang;"
        htmlEncodeChars['\u232A'] = "&rang;"
        htmlEncodeChars['\u25CA'] = "&loz;"
        htmlEncodeChars['\u2660'] = "&spades;"
        htmlEncodeChars['\u2663'] = "&clubs;"
        htmlEncodeChars['\u2665'] = "&hearts;"
        htmlEncodeChars['\u2666'] = "&diams;"
    }
}